name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: Run Tests and Handle Logs
    runs-on: depot-ubuntu-22.04-4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Depot CLI
      uses: depot/setup-action@v1
      env:
        DEPOT_TOKEN: ${{ secrets.DEPOT_API_TOKEN }}

    - name: Build and load Docker image with Depot
      run: |
        depot build . \
          --project 2g4vskn96j \
          --file Dockerfile \
          --tag ${{ env.REGISTRY }}/${{ github.repository }}:latest \
          --platform linux/amd64 \
          --build-arg RELEASE=--release \
          --build-arg ARCH=amd64 \
          --build-arg RELEASE_DIR=release \
          --load
      env:
        DEPOT_TOKEN: ${{ secrets.DEPOT_API_TOKEN }}

    - name: Run Docker container
      run: docker run -p 127.0.0.1:3033:3033 -v $PWD/data:/data -e RUN_TESTS=true ${{ env.REGISTRY }}/${{ github.repository }}:latest

    - name: Copy and handle logs
      if: ${{ always() }}
      run: |
          CONTAINER_ID=$(docker ps -aq --latest --filter "status=exited")
          if [ -z "$CONTAINER_ID" ]; then
            echo "No recently exited containers found."
            exit 1
          fi
          docker cp $CONTAINER_ID:/tmp/ /tmp/container_tmp/
          mkdir -p /tmp/logs
          find /tmp/container_tmp/ -name "*.log" -exec mv {} /tmp/logs/ \;
          if [ "$(ls -A /tmp/logs/)" ]; then
            zip -j /tmp/log-files.zip /tmp/logs/*.log
            echo "Logs zipped successfully."
          else
            echo "No log files found"
          fi

    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: log-files.zip
        path: /tmp/log-files.zip
