name: rust fmt check

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - '*' 

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install/update rustfmt
      run: |
        rustup update
        rustup component add rustfmt 
    - name: Check formatting
      run: cargo fmt -- --check
